version: "3.9"

services:
  frontend:
    build: .
    container_name: vue-dev
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    image: nginx:stable-alpine
    container_name: vue-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
